# fly.toml app configuration file generated for thqnam-nextjs-anycable on 2026-09-01T12:29:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thqnam-anycable-go'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 16
  memory_mb = 32768
