# fly.toml app configuration file generated for thqnam-anycable-go on 2026-09-03T13:06:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thqnam-anycable-go'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '2gb'
  memory_mb = 2048
  processes = ['app']
  size = 'shared-cpu-1x'
